downstream_package_name: rear
jobs:
- job: copr_build
  metadata:
    targets:
          - fedora-36-x86_64
          - centos-stream-8-x86_64
  trigger: pull_request
- job: tests
  trigger: pull_request
  metadata:
    targets:
      - fedora-36-x86_64
      - centos-stream-8-x86_64
specfile_path: packaging/rpm/rear.spec
synced_files:
- .packit.yaml
- dest: rear.spec
  src: packaging/rpm/rear.spec
upstream_project_name: rear
