downstream_package_name: rear
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-35-x86_64
  trigger: pull_request
specfile_path: packaging/rpm/rear.spec
synced_files:
- .packit.yaml
- dest: rear.spec
  src: packaging/rpm/rear.spec
upstream_project_name: rear
