---

name: Differential ShellCheck
on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: antonvoznia/differential-shellcheck@acbe2cf23d1130e08e3fd7517a6b6ab5ab9b6ee8
        with:
          severity: style
          token: ${{ secrets.GITHUB_TOKEN }}
