---

name: Differential ShellCheck
on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: antonvoznia/differential-shellcheck@97f3bf7a025a14d3e28bc5d96b065b6d783d2fd8
        with:
          severity: error
          token: ${{ secrets.GITHUB_TOKEN }}
