---

name: Differential ShellCheck
on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: antonvoznia/differential-shellcheck@a0b4529d696383c2d97222d354e5a83e2884a63f
        with:
          severity: error
          token: ${{ secrets.GITHUB_TOKEN }}
