# https://github.com/marketplace/actions/pipeline-components-shellcheck

on:
  pull_request:
    branch:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    stage: linting
    image: pipelinecomponents/shellcheck:latest
    script:
      - |
        find . -name .git -type d -prune -o -type f -name \*.sh -print0 |
        xargs -0 -r -n1 shellcheck
        
    - name: pipeline-components-shellcheck
      uses: pipeline-components/shellcheck@v0.6.0


