name: Differential ShellCheck
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellCheck:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v2.1.0
        with:
          ignored-codes: .github/.diff-shellcheck-exceptions.txt
          shell-scripts: .github/.diff.shellcheck-scripts.txt
