# https://github.com/marketplace/actions/shell-linter

on:
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest

